#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
#http://stackoverflow.com/questions/242538/unix-shell-script-find-out-which-directory-the-script-file-resides
#Pull values from config INI
source <(grep = ${SCRIPTPATH}/manager-config.ini)
#sed "s/;/#/g" manager-config.ini | source /dev/stdin
MAX_PLAYERS=`echo ${MAX_PLAYERS} | sed -e 's/\r//g'`
GALAXY=`echo ${GALAXY} | sed -e 's/\r//g'`
PARAMS=`echo ${PARAMS} | sed -e 's/\r//g'`
PORT=`echo ${PORT} | sed -e 's/\r//g'`
LOG_ROTATION=`echo ${LOG_ROTATION} | sed -e 's/\r//g'`
AutoRestart=`echo ${AutoRestart} | sed -e 's/\r//g'`
DAILYRESTART=`echo ${DailyRestart} | sed -e 's/\r//g'`
BETA=`echo ${BETA} | sed -e 's/\r//g'`
WEBPORT=`echo ${WEBPORT} | sed -e 's/\r//g'`
IPAddress=`echo ${IPAddress} | sed -e 's/\r//g'`
GetSectorDataInterval=`echo ${GetSectorDataInterval} | sed -e 's/\r//g'`
GetPlayerDataInterval=`echo ${GetPlayerDataInterval} | sed -e 's/\r//g'`
GetAllianceDataInterval=`echo ${GetAllianceDataInterval} | sed -e 's/\r//g'`
CustomCronjob_1=`echo ${CustomCronjob_1} | sed -e 's/\r//g'`
CustomCronjob_2=`echo ${CustomCronjob_2} | sed -e 's/\r//g'`
CustomCronjob_3=`echo ${CustomCronjob_3} | sed -e 's/\r//g'`
CustomCronjob_4=`echo ${CustomCronjob_4} | sed -e 's/\r//g'`
CustomCronjob_5=`echo ${CustomCronjob_5} | sed -e 's/\r//g'`

# Colors
WHITE='\033[1;37m'
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
PURPLE='\033[1;35m'
NOCOLOR='\033[0m'
# Static - Dont change these
VERSION=1.1.7
APPID=565060
SERVER=${GALAXY}_Server
TMUX_SESSION=${GALAXY}_Tmux
INSTALL_DIR=$SCRIPTPATH/serverfiles
STEAM_DIR=$SCRIPTPATH/steamcmd
T='tmux send-keys -t '${TMUX_SESSION}':0.0'
# Auto Restart
CRONJOB='0,5,10,15,20,25,30,35,40,45,50,55 * * * * '${SCRIPTPATH}'/manager status -o CRON >> '${SCRIPTPATH}'/avorion-manager/logs/$(/bin/date +\%d-\%m-\%Y)_status.log'
CRONDAILYRESTART_NOW='41 11,23 * * * '${SCRIPTPATH}'/manager restart -o CRON -d 15 -b "Restarting Server" >> '${SCRIPTPATH}'/avorion-manager/logs/$(/bin/date +\%d-\%m-\%Y)_status.log'
UpdateServerLog='* * * * * '${SCRIPTPATH}'/manager proc -o CRON'
CRONSECTORDATA='nice -n 10 '${SCRIPTPATH}'/manager get_sector_data -o CRON'
CRONPLAYERDATA='nice -n 15 '${SCRIPTPATH}'/manager get_player_data -o CRON'
CRONALLIANCEDATA='nice -n 15 '${SCRIPTPATH}'/manager get_alliance_data -o CRON'
RequiredCommand=$1
SecondCommand=''
verbose='false'
output=''
broadcast=''
delay=''
force='false'
DisplayDescription=''

# skip past the first required command
shift

# skip past the second command
valid='[-.]'
if [[ ! "$1" =~ $valid ]]; then
  SecondCommand=$1
  shift
fi

while getopts 'd:b:o:vhf' flag; do
  case "${flag}" in
    o) output="${OPTARG}" ;;
    b) broadcast="${OPTARG}" ;;
    d) delay="${OPTARG}" ;;
    v) verbose='true' ;;
    h) DisplayDescription='true' ;;
    f) force='true' ;;
    *) error "Unexpected option ${flag}" ;;
  esac
done

if [ ! -z "$broadcast" ]; then
  if [ "$verbose" = true ]; then
    DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} Broadcasting message: $broadcast, will append delay time if \-d is used"
  fi
  if [ -z "$delay" ]; then
    $T '/say [SERVER] '"${broadcast}" C-m
  fi
fi

if [ ! -z "$delay" ]; then
  re='^[0-9]+$'
  if ! [[ $delay =~ $re ]] ; then
     echo "error: Not a number" >&2; exit 1
  fi
  if [ "$verbose" = true ] ; then
    DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} Command suspeneded for $delay minutes"
  fi
  minutes=$delay
  while [ $minutes -gt 0 ]; do
    if [ "$verbose" = true ] ; then
      DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} $minutes minutes until running command."
    fi
    if [ ! -z "$broadcast" ]; then
      if pidof ${SERVER} > /dev/null
  		then
        $T '/say [SERVER] '"${broadcast}"' in '"${minutes}"' minutes.' C-m
      else
        if [ "$verbose" = true ] ; then
          DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} is not running!"
        fi
      fi
    fi
    sleep 60
    minutes=$(($minutes-1))
  done
fi

DynamicEcho() {
  # Second Argument used to detect who were echoing too.

  if [ "$output" = "CRON" ]; then
      if [ "$2" != "DONTLOG" ]; then
          echo -e -n $(date +"%F %H-%M-00| "); echo -e '[Manager]: '$1 | sed -r 's/'$(echo -e "\033")'\[[0-9]{1,2}(;([0-9]{1,2})?)?[mK]//g'
      fi
  elif [ "$output" = "PHP" ]; then
    if [ "$2" != "DONTLOG" ]; then
      echo -e $1'\n' | sed -r 's/'$(echo -e "\033")'\[[0-9]{1,2}(;([0-9]{1,2})?)?[mK]//g'
    fi
  else
    if [ "$2" != "DONTLOG" ]; then
      echo -e "${WHITE}[Manager]${NOCOLOR}: $1"
    else
      echo -en "$1"
    fi
  fi
}
DeleteCronJobs(){
  crontab -l | grep -v "${SCRIPTPATH}/manager"  | crontab -
  crontab -l | grep -v "${SCRIPTPATH}/avorion-manager"  | crontab -
  crontab -l | grep -v "${CustomCronjob_1}"  | crontab -
  crontab -l | grep -v "${CustomCronjob_2}"  | crontab -
  crontab -l | grep -v "${CustomCronjob_3}"  | crontab -
  crontab -l | grep -v "${CustomCronjob_4}"  | crontab -
  crontab -l | grep -v "${CustomCronjob_5}"  | crontab -
}
CreateCronJobs(){
  if [ "${DAILYRESTART}" = true ]; then
    (crontab -l ; echo "${CRONDAILYRESTART_NOW}") | crontab -
  fi
  (crontab -l ; echo "${UpdateServerLog}") | crontab -
  (crontab -l ; echo "0 ${GetSectorDataInterval} * * * ${CRONSECTORDATA}") | crontab -
  (crontab -l ; echo "${GetPlayerDataInterval} * * * * ${CRONPLAYERDATA}") | crontab -
  (crontab -l ; echo "${GetAllianceDataInterval} * * * * ${CRONALLIANCEDATA}") | crontab -
  (crontab -l ; echo "${CRONJOB}") | crontab -
  (crontab -l ; echo "${CustomCronjob_1}") | crontab -
  (crontab -l ; echo "${CustomCronjob_2}") | crontab -
  (crontab -l ; echo "${CustomCronjob_3}") | crontab -
  (crontab -l ; echo "${CustomCronjob_4}") | crontab -
  (crontab -l ; echo "${CustomCronjob_5}") | crontab -
}
LogToManagerLog(){
  echo -e -n $(date +"%F %H-%M-%S| ") >> ${SCRIPTPATH}/avorion-manager/logs/$(/bin/date +\%d-\%m-\%Y)_manager.log
  echo -e "[Manager]: $1" >> ${SCRIPTPATH}/avorion-manager/logs/$(/bin/date +\%d-\%m-\%Y)_manager.log

  #Status.log rotation
  find ${SCRIPTPATH}/avorion-manager/logs/*_manager.log -mtime +${LOG_ROTATION} -type f -delete 2> /dev/null
  find ${SCRIPTPATH}/avorion-manager/logs/*_status.log -mtime +${LOG_ROTATION} -type f -delete 2> /dev/null
  find ${SCRIPTPATH}/avorion-manager/logs/*_playerchat.log -mtime +${LOG_ROTATION} -type f -delete 2> /dev/null
}

DisplayHelp(){
  DynamicEcho "available commands:\n           ${GREEN}start${NOCOLOR} server,\n           ${GREEN}stop${NOCOLOR} server,\n           ${GREEN}restart${NOCOLOR} server,\n           check server's ${GREEN}status${NOCOLOR},\n           check for ${GREEN}update${NOCOLOR}s,\n           ${GREEN}attach${NOCOLOR} to console,\n           show this ${GREEN}help${NOCOLOR},\n           ${GREEN}install${NOCOLOR} steamcmd,\n           ${GREEN}start-web${NOCOLOR} starts php server\n           ${GREEN}stop-web${NOCOLOR} Stops PHP server\n           ${GREEN}enablerestart${NOCOLOR} Adds restart cron jobs,\n           ${GREEN}disablerestart${NOCOLOR} Removes restart cron jobs,\n           ${GREEN}get_alliance_data${NOCOLOR} for the web interface,\n           ${GREEN}get_player_data${NOCOLOR} for the web interface,\n           ${GREEN}get_sector_data${NOCOLOR} for the web interface,\n           ${GREEN}apache_install${NOCOLOR} so the web interface can run off of apache (must be root/sudo),"
  echo ""
  DynamicEcho "available options:\n           ${GREEN}-h${NOCOLOR}                --Shows description of command\n           ${GREEN}-d${NOCOLOR} #              --Delay time in minutes\n           ${GREEN}-b${NOCOLOR} \"Message\"      --Broadcast message every minute of the delay\n           ${GREEN}-v${NOCOLOR}                --verbose output\n           ${GREEN}-o${NOCOLOR} [CRON/PHP]     --Displays message without coloring"
}

LoadFile(){
  requested_file="${1}"
  if [ "${2}" ]; then
    SecondCommand="${2}"
  fi

  file_path="${SCRIPTPATH}/avorion-manager/manager/${requested_file}"
  if [ -f "${file_path}" ]; then
    chmod +x "${file_path}"
    LogToManagerLog "Executing: ${RequiredCommand}";
    source "${file_path}"
  else
    DisplayHelp;
  fi
}


LoadFile "${RequiredCommand}.sh"
